costCode: CC98112
projectCode: aazzxxyy
infra:
    zone: a,b,c
    region: us-e
tags:
    machine: frontdrive
    rack: 4c
    drive: ssd
    vcard: 8g
LangUsed:
    - ruby
    - go
    - scala
    - java
mysubchart:
    dbhostname: procmysqlnode